[versions]
agpVersion = "8.13.0"
kotlinVersion = "2.2.21"
coreKtxVersion = "1.17.0"
lifecycleRuntimeKtxVersion = "2.9.4"
activityComposeVersion = "1.11.0"
composeBomVersion = "2025.10.01"
kotlinXImmutableCollectionsVersion = "0.4.0"
ktlintVersion = "13.1.0"
koinBomVersion = "4.1.1"
kotlinxSerializationVersion = "1.9.0"
nav3CoreVersion = "1.0.0-beta01"
lifecycleViewmodelNav3Version = "2.10.0-beta01"
kotlinxSerializationCoreVersion = "1.9.0"
material3AdaptiveNav3Version = "1.3.0-alpha02"

[libraries]
kotlinXImmutableCollectionsLibrary = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinXImmutableCollectionsVersion" }
androidxCoreKtxLibrary = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
androidxLifecycleRuntimeKtxLibrary = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidxActivityComposeLibrary = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }
androidxComposeBomLibrary = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBomVersion" }
androidxComposeUiLibrary = { group = "androidx.compose.ui", name = "ui" }
androidxComposeUiGraphicsLibrary = { group = "androidx.compose.ui", name = "ui-graphics" }
androidxComposeUiToolingLibrary = { group = "androidx.compose.ui", name = "ui-tooling" }
androidxComposeUiToolingPreviewLibrary = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidxComposeUiTestManifestLibrary = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidxComposeMaterial3Library = { group = "androidx.compose.material3", name = "material3" }
koinBomLibrary = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinBomVersion" }
koinCoreLibrary = { group = "io.insert-koin", name = "koin-core" }
koinAndroidLibrary = { group = "io.insert-koin", name = "koin-android" }
koinCoroutinesLibrary = { group = "io.insert-koin", name = "koin-core-coroutines" }
koinStartupLibrary = { group = "io.insert-koin", name = "koin-androidx-startup" }
koinComposeLibrary = { group = "io.insert-koin", name = "koin-androidx-compose" }
koinComposeNavigationLibrary = { group = "io.insert-koin", name = "koin-androidx-compose-navigation" }
kotlinXSerializationLibrary = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }
androidxNavigation3RuntimeLibrary = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3CoreVersion" }
androidxNavigation3UiLibrary = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3CoreVersion" }
androidxLifecycleViewmodelNavigation3Library = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3Version" }
kotlinxSerializationCoreLibrary = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCoreVersion" }
androidxMaterial3AdaptiveNavigation3Library = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3Version" }

[bundles]
navBundle = [
    "androidxNavigation3UiLibrary",
    "androidxNavigation3RuntimeLibrary",
    "androidxLifecycleViewmodelNavigation3Library",
    "androidxMaterial3AdaptiveNavigation3Library",
]
composeImplementationBundle = [
    "androidxComposeUiLibrary",
    "androidxComposeUiGraphicsLibrary",
    "androidxComposeUiToolingPreviewLibrary",
    "androidxComposeMaterial3Library",
]
composeDebugImplementationBundle = [
    "androidxComposeUiToolingLibrary",
    "androidxComposeUiToolingPreviewLibrary",
    "androidxComposeUiTestManifestLibrary",
]
koinBundle = [
    "koinCoreLibrary",
    "koinAndroidLibrary",
    "koinCoroutinesLibrary",
    "koinStartupLibrary",
    "koinComposeLibrary",
    "koinComposeNavigationLibrary",
]
dataStorageBundle = [
    "kotlinXSerializationLibrary",
    "kotlinXImmutableCollectionsLibrary",
]

[plugins]
androidApplicationPlugin = { id = "com.android.application", version.ref = "agpVersion" }
kotlinAndroidPlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
kotlinComposePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
ktlintPlugin = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintVersion" }
androidLibraryPlugin = { id = "com.android.library", version.ref = "agpVersion" }
kotlinSerializationPlugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }

