[versions]
agpVersion = "8.13.0"
kotlinVersion = "2.2.21"
coreKtxVersion = "1.17.0"
lifecycleRuntimeKtxVersion = "2.9.4"
activityComposeVersion = "1.11.0"
composeBomVersion = "2025.10.01"
kotlinXImmutableCollectionsVersion = "0.4.0"
ktlintVersion = "13.1.0"
koinBomVersion = "4.1.1"
kotlinxSerializationVersion = "1.9.0"
nav3CoreVersion = "1.0.0-beta01"
lifecycleViewmodelNav3Version = "2.10.0-beta01"
kotlinxSerializationCoreVersion = "1.9.0"
material3AdaptiveNav3Version = "1.3.0-alpha02"
detektVersion = "1.23.8"
junitVersion = "4.13.2"
truthVersion = "1.4.5"
turbineVersion = "1.2.1"
archUnitJUnit4Version = "1.4.1"
roboelectricVersion = "4.16"
preferencesDataStoreVersion = "1.1.7"
roomVersion = "2.8.3"
kspVersion = "2.2.21-2.0.4"
moduleGraphVersion = "0.13.0"
conventionPluginAndroidApplicationName = "androidApplicationPlugin"
conventionPluginAndroidApplicationClass = "com.sarim.convention.AndroidApplicationConventionPlugin"
conventionPluginDiLibraryName = "diLibraryPlugin"
conventionPluginDiLibraryClass = "com.sarim.convention.AndroidDiLibraryConventionPlugin"
conventionPluginDataLibraryName = "dataLibraryPlugin"
conventionPluginDataLibraryClass = "com.sarim.convention.AndroidDataLibraryConventionPlugin"
conventionPluginDomainLibraryName = "domainLibraryPlugin"
conventionPluginDomainLibraryClass = "com.sarim.convention.AndroidDomainLibraryConventionPlugin"
conventionPluginPresentationLibraryName = "presentationLibraryPlugin"
conventionPluginPresentationLibraryClass = "com.sarim.convention.AndroidPresentationLibraryConventionPlugin"
conventionPluginNavLibraryName = "navLibraryPlugin"
conventionPluginNavLibraryClass = "com.sarim.convention.AndroidNavLibraryConventionPlugin"
conventionPluginUtilsLibraryName = "utilsLibraryPlugin"
conventionPluginUtilsLibraryClass = "com.sarim.convention.AndroidUtilsLibraryConventionPlugin"
junit = "1.3.0"
espressoCoreVersion = "3.7.0"
appcompatVersion = "1.7.1"
materialVersion = "1.13.0"

[libraries]
kotlinXImmutableCollectionsLibrary = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinXImmutableCollectionsVersion" }
androidxCoreKtxLibrary = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
androidxLifecycleRuntimeKtxLibrary = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidxActivityComposeLibrary = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }
androidxComposeBomLibrary = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBomVersion" }
androidxComposeUiLibrary = { group = "androidx.compose.ui", name = "ui" }
androidxComposeUiGraphicsLibrary = { group = "androidx.compose.ui", name = "ui-graphics" }
androidxComposeUiToolingLibrary = { group = "androidx.compose.ui", name = "ui-tooling" }
androidxComposeUiToolingPreviewLibrary = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidxComposeUiTestManifestLibrary = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidxComposeMaterial3Library = { group = "androidx.compose.material3", name = "material3" }
koinBomLibrary = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinBomVersion" }
koinCoreLibrary = { group = "io.insert-koin", name = "koin-core" }
koinAndroidLibrary = { group = "io.insert-koin", name = "koin-android" }
koinCoroutinesLibrary = { group = "io.insert-koin", name = "koin-core-coroutines" }
koinStartupLibrary = { group = "io.insert-koin", name = "koin-androidx-startup" }
koinComposeLibrary = { group = "io.insert-koin", name = "koin-androidx-compose" }
koinComposeNavigationLibrary = { group = "io.insert-koin", name = "koin-androidx-compose-navigation" }
kotlinXSerializationLibrary = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }
androidxNavigation3RuntimeLibrary = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3CoreVersion" }
androidxNavigation3UiLibrary = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3CoreVersion" }
androidxLifecycleViewmodelNavigation3Library = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3Version" }
kotlinxSerializationCoreLibrary = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCoreVersion" }
androidxMaterial3AdaptiveNavigation3Library = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3Version" }
androidGradlePluginLibrary = { group = "com.android.tools.build", name = "gradle", version.ref = "agpVersion" }
kotlinGradlePluginLibrary = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinVersion" }
kotlinSerializationPluginLibrary = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlinVersion" }
junitLibrary = { group = "junit", name = "junit", version.ref = "junitVersion" }
archUnitJUnit4Library = { group = "com.tngtech.archunit", name = "archunit-junit4", version.ref = "archUnitJUnit4Version" }
truthLibrary = { group = "com.google.truth", name = "truth", version.ref = "truthVersion" }
turbineLibrary = { group = "app.cash.turbine", name = "turbine", version.ref = "turbineVersion" }
roboelectricLibrary = { group = "org.robolectric", name = "robolectric", version.ref = "roboelectricVersion" }
dataStoreLibrary = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "preferencesDataStoreVersion" }
roomRunTimeLibrary = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
roomCompilerLibrary = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
roomKtxLibrary = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCoreVersion" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }

[bundles]
navBundle = [
    "androidxNavigation3UiLibrary",
    "androidxNavigation3RuntimeLibrary",
    "androidxLifecycleViewmodelNavigation3Library",
    "androidxMaterial3AdaptiveNavigation3Library",
]
composeImplementationBundle = [
    "androidxComposeUiLibrary",
    "androidxComposeUiGraphicsLibrary",
    "androidxComposeMaterial3Library",
]
composeDebugImplementationBundle = [
    "androidxComposeUiToolingLibrary",
    "androidxComposeUiToolingPreviewLibrary",
    "androidxComposeUiTestManifestLibrary",
]
koinBundle = [
    "koinCoreLibrary",
    "koinAndroidLibrary",
    "koinCoroutinesLibrary",
    "koinStartupLibrary",
    "koinComposeLibrary",
    "koinComposeNavigationLibrary",
]
dataStorageBundle = [
    "kotlinXSerializationLibrary",
    "kotlinXImmutableCollectionsLibrary",
    "dataStoreLibrary",
    "roomRunTimeLibrary",
    "roomKtxLibrary",
]
testBundle = [
    "junitLibrary",
    "archUnitJUnit4Library",
    "truthLibrary",
    "turbineLibrary",
    "roboelectricLibrary",
]

[plugins]
androidApplicationPlugin = { id = "com.android.application", version.ref = "agpVersion" }
kotlinAndroidPlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
kotlinComposePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
ktlintPlugin = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintVersion" }
androidLibraryPlugin = { id = "com.android.library", version.ref = "agpVersion" }
kotlinSerializationPlugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
moduleGraphPlugin = { id = "dev.iurysouza.modulegraph", version.ref = "moduleGraphVersion" }
detektPlugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektVersion" }
conventionPluginAndroidApplicationId = { id = "com.sarim.convention.android.application.plugin" }
conventionPluginDiLibraryId = { id = "com.sarim.convention.android.di.library.plugin" }
conventionPluginDataLibraryId = { id = "com.sarim.convention.android.data.library.plugin" }
conventionPluginDomainLibraryId = { id = "com.sarim.convention.domain.library.plugin" }
conventionPluginPresentationLibraryId = { id = "com.sarim.convention.presentation.library.plugin" }
conventionPluginNavLibraryId = { id = "com.sarim.convention.nav.library.plugin" }
conventionPluginUtilsLibraryId = { id = "com.sarim.convention.utils.library.plugin" }
